# =========================================================
# TLS 1.3 + 单向 TLS 客户端
# =========================================================
tls.name=demo-client-tls13-none
tls.protocols=TLSv1.3
tls.cipherSuites=
tls.clientAuthentication.mode=NONE

tls.trustStore.type=PKCS12
tls.trustStore.path=certs/openssl/client-truststore.p12
tls.trustStore.passwordKey=TLS_TRUSTSTORE_PASSWORD

tls.hostnameVerification.enabled=true
tls.connectTimeoutMillis=5000
tls.handshakeTimeoutMillis=10000
tls.socketTimeoutMillis=30000

demo.peer.host=localhost
demo.peer.port=8443
demo.message=Hello, TLS 1.3 one-way!
