package com.example.tls.demo.config;

import com.example.tls.config.EndpointRole;
import com.example.tls.security.PasswordProvider;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;

/**
 * Demo-only password fallback: reads the random password files generated by
 * {@code scripts/openssl} or {@code scripts/keytool}. This exists so the demo
 * can be started directly from an IDE without exporting environment variables.
 *
 * <p>Security boundaries:
 * <ul>
 *   <li>Files are chmod 600 and covered by .gitignore;</li>
 *   <li>the fallback is used only when env/system-property providers have no value;</li>
 *   <li>this class lives in the demo layer and is not part of the reusable core.</li>
 * </ul>
 */
public final class LocalScriptPasswordProvider implements PasswordProvider {

    private final EndpointRole role;

    public LocalScriptPasswordProvider(EndpointRole role) {
        this.role = role;
    }

    @Override
    public Optional<char[]> lookup(String secretName) {
        String fileName = fileNameFor(secretName);
        if (fileName == null) {
            return Optional.empty();
        }
        for (Path directory : candidateDirectories()) {
            Path file = directory.resolve(fileName);
            if (Files.isRegularFile(file)) {
                try {
                    return Optional.of(Files.readString(file).trim().toCharArray());
                } catch (IOException ignored) {
                    return Optional.empty();
                }
            }
        }
        return Optional.empty();
    }

    /**
     * Map symbolic secret names to the files produced by the demo scripts.
     * Server/Client each have their own key store and trust store password.
     */
    private String fileNameFor(String secretName) {
        String prefix = role == EndpointRole.SERVER ? "server" : "client";
        switch (secretName) {
            case "TLS_KEYSTORE_PASSWORD" -> {
                return prefix + "-keystore.password";
            }
            case "TLS_TRUSTSTORE_PASSWORD" -> {
                return prefix + "-truststore.password";
            }
            default -> {
                return null;
            }
        }
    }

    private static List<Path> candidateDirectories() {
        return List.of(
                Path.of("certs", "openssl").toAbsolutePath(),
                Path.of("certs", "keytool").toAbsolutePath());
    }

    @Override
    public String toString() {
        return "LocalScriptPasswordProvider{role=" + role + "}";
    }
}
