# =========================================================
# TLS 1.2 + 单向 TLS 客户端：只需要 TrustStore 验证 Server。
# =========================================================
tls.name=demo-client-tls12-none
tls.protocols=TLSv1.2
tls.cipherSuites=
tls.clientAuthentication.mode=NONE

tls.trustStore.type=PKCS12
tls.trustStore.path=certs/openssl/client-truststore.p12
tls.trustStore.passwordKey=TLS_TRUSTSTORE_PASSWORD

tls.hostnameVerification.enabled=true
tls.connectTimeoutMillis=5000
tls.handshakeTimeoutMillis=10000
tls.socketTimeoutMillis=30000

demo.peer.host=localhost
demo.peer.port=8443
demo.message=Hello, TLS 1.2 one-way!
