# =========================================================
# 示例：TLS 1.2 + 显式 Cipher Suite 严格白名单
# =========================================================
tls.name=demo-server-cipher-whitelist-tls12
tls.protocols=TLSv1.2
tls.cipherSuites=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
tls.clientAuthentication.mode=NONE

tls.keyStore.type=PKCS12
tls.keyStore.path=certs/openssl/server.p12
tls.keyStore.passwordKey=TLS_KEYSTORE_PASSWORD

tls.hostnameVerification.enabled=true
tls.connectTimeoutMillis=5000
tls.handshakeTimeoutMillis=10000
tls.socketTimeoutMillis=30000

demo.peer.host=localhost
demo.peer.port=8443
